name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run tests and build JAR
      run: mvn clean package
      
    - name: Get JAR file name
      id: jar
      run: |
        JAR_FILE=$(find target -name "*.jar" -not -name "original-*" | head -1)
        echo "file=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "name=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.jar.outputs.file }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}